---
openapi: 3.1.0
info:
  title: API - Daniesteb DEV - Data Import
  description: API to data import from file to database
  contact:
    name: Daniesteb DEV - Daniel Jimenez
    email: danielejimeneza@gmail.com
  version: 1.1.0
servers:
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/DanielJimenez-287/ded-msa-data-import/1.0.0
  - description: Development
    url: http://localhost:8080/api/daniesteb-dev/v1
tags:
  - name: Data Import
    description: Data Import Controller
paths:
  /data-imports:
    post:
      tags:
        - Data Import
      summary: The endpoint that import data from file to database
      description: Data import
      operationId: PostDataImport
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                  description: binary file to process
                  examples:
                    - SGVsbG8sIFdvcmxkIQ
                fileTemplateType:
                  type: string
                  description: File template type to process
                  minLength: 1
                  maxLength: 100
                  examples:
                    - seating
        description: Data to connect datasource
      responses:
        "200":
          description: data imported
          content:
            application/json:
              schema:
                type: object
                properties:
                  fileDetailErrors:
                    type: array
                    items:
                      type: object
                      properties:
                        line:
                          type: string
                          minLength: 2
                          maxLength: 150
                          description: Line of file with error
                          examples:
                            - L6
                        description:
                          type: string
                          description: Error description
                          examples:
                            - Empty value field
                        value:
                          type: string
                          description: Value to be processed in the service
                          examples:
                            - 10047
        "400":
          description: "invalid input, object invalid"
  /data-imports/upload:
    post:
      tags:
        - Data Import
      summary: The endpoint that import data from file to database
      description: Data import
      operationId: PostDataImportUpload
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                  description: binary file to process
                  examples:
                    - SGVsbG8sIFdvcmxkIQ
        description: Data to connect datasource
      responses:
        "200":
          description: data imported
          content:
            application/json:
              schema:
                type: object
                properties:
                  fileId:
                    type: string
                    description: Upload file fileId
                    minLength: 36
                    maxLength: 36
                    pattern: "^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$"
                    examples:
                      - 7db919d8-0546-466a-8089-6ac580a0bec51367374247113519371
        "400":
          description: "invalid input, object invalid"
  /data-imports/validate:
    post:
      tags:
        - Data Import
      summary: The endpoint that import data from file to database
      description: Data import
      operationId: PostDataImportValidate
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                fileId:
                  type: string
                  description: Upload file fileId
                  minLength: 36
                  maxLength: 36
                  pattern: "^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$"
                  examples:
                    - 7db919d8-0546-466a-8089-6ac580a0bec51367374247113519371
                fileTemplateType:
                  type: string
                  description: File template type to process
                  minLength: 1
                  maxLength: 100
                  examples:
                    - seating
      responses:
        "200":
          description: data imported
          content:
            application/json:
              schema:
                type: object
                properties:
                  fileDetailErrors:
                    type: array
                    items:
                      type: object
                      properties:
                        line:
                          type: string
                          minLength: 2
                          maxLength: 150
                          description: Line of file with error
                          examples:
                            - L6
                        description:
                          type: string
                          description: Error description
                          examples:
                            - Empty value field
                        value:
                          type: string
                          description: Value to be processed in the service
                          examples:
                            - 10047
        "400":
          description: "invalid input, object invalid"
components:
  parameters:
    FileToProcess:
      in: header
      name: fileToProcess
      description: The file to process
      schema:
        type: string
        format: base64
  schemas:
    PostDataImportRequest:
      type: object
      properties:
        file:
          type: string
          format: binary
          description: binary file to process
          examples:
            - SGVsbG8sIFdvcmxkIQ
        fileTemplateType:
          type: string
          description: File template type to process
          minLength: 1
          maxLength: 100
          examples:
            - seating
    PostDataImportResponse:
      type: object
      properties:
        fileDetailErrors:
          type: array
          items:
            type: object
            properties:
              line:
                type: string
                minLength: 2
                maxLength: 150
                description: Line of file with error
                examples:
                  - L6
              description:
                type: string
                description: Error description
                examples:
                  - Empty value field
              value:
                type: string
                description: Value to be processed in the service
                examples:
                  - 10047
    PostDataImportValidateRequest:
      type: object
      properties:
        fileId:
          type: string
          description: Upload file fileId
          minLength: 36
          maxLength: 36
          pattern: "^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$"
          examples:
            - 7db919d8-0546-466a-8089-6ac580a0bec51367374247113519371
        fileTemplateType:
          type: string
          description: File template type to process
          minLength: 1
          maxLength: 100
          examples:
            - seating
    PostDataImportValidateResponse:
      type: object
      properties:
        fileDetailErrors:
          type: array
          items:
            type: object
            properties:
              line:
                type: string
                minLength: 2
                maxLength: 150
                description: Line of file with error
                examples:
                  - L6
              description:
                type: string
                description: Error description
                examples:
                  - Empty value field
              value:
                type: string
                description: Value to be processed in the service
                examples:
                  - 10047
    PostDataImportUploadRequest:
      type: object
      properties:
        file:
          type: string
          format: binary
          description: binary file to process
          examples:
            - SGVsbG8sIFdvcmxkIQ
    PostDataImportUploadResponse:
      type: object
      properties:
        fileId:
          type: string
          description: Upload file fileId
          minLength: 36
          maxLength: 36
          pattern: "^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$"
          examples:
            - 7db919d8-0546-466a-8089-6ac580a0bec51367374247113519371
    FileDetailError:
      type: object
      properties:
        line:
          type: string
          minLength: 2
          maxLength: 150
          description: Line of file with error
          examples:
            - L6
        description:
          type: string
          description: Error description
          examples:
            - Empty value field
        value:
          type: string
          description: Value to be processed in the service
          examples:
            - 10047
    FileInfo:
      type: object
      properties:
        fileId:
          type: string
          description: Upload file fileId
          minLength: 36
          maxLength: 36
          pattern: "^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$"
          examples:
            - 7db919d8-0546-466a-8089-6ac580a0bec51367374247113519371
        fileTemplateType:
          type: string
          description: File template type to process
          minLength: 1
          maxLength: 100
          examples:
            - seating
    FileId:
      type: string
      description: Upload file fileId
      minLength: 36
      maxLength: 36
      pattern: "^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$"
      examples:
        - 7db919d8-0546-466a-8089-6ac580a0bec51367374247113519371
    FileTemplateType:
      type: string
      description: File template type to process
      minLength: 1
      maxLength: 100
      examples:
        - seating
    File:
      type: string
      format: binary
      description: binary file to process
      examples:
        - SGVsbG8sIFdvcmxkIQ
